/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "rtos_list.h"
#include "rtos_thread.h"
#include "rtos.h"

rtos_thread_t thread1;
rtos_stack_t stack1;
void threadmain1(void){
	uint32_t i = 0;
	i++;
}

int main(void)
{
	/* Initialize the RTOS */
	rtos_init();
	/* Configure and enable SysTick interrupts */
	rtos_svc_threadCreate(&thread1, &stack1, 1, threadmain1);
	/* Loop forever */
	while(1){}
}
