/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"

#define SYSTEM_CORE_CLOCK_HZ                 ((uint32_t) 16000000u)
#define SYS_TICK_RATE_HZ                     ((uint32_t) 1000u)
/**
 * @brief   thread1function
 * @note
 * @param   none
 * @retval  none
 */
void thread1function(void)
{
  while(1)
  {
    for (int var = 0; var < 1000000; ++var)
    {
    }
  }
}
/**
 * @brief   thread2function
 * @note
 * @param   none
 * @retval  none
 */
void thread2function(void)
{

  while(1)
  {
    for (int var = 0; var < 1000000; ++var)
    {
    }
  }
}

int main(void)
{
	/* Configure and enable SysTick interrupts */
	SysTick_Config(SYSTEM_CORE_CLOCK_HZ / SYS_TICK_RATE_HZ);
    /* Loop forever */
  while(1){
    /* Do nothing */
  }
}
