/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "rtos_list.h"
#include "rtos_thread.h"
#include "rtos.h"
#include "rtos_mutex.h"

rtos_thread_t thread1;
rtos_stack_t stack1;
rtos_thread_t thread2;
rtos_stack_t stack2;
rtos_mutex_t mutex1;

void threadmain1(void){
	rtos_svc_mutexLock(&mutex1,0u);
	while(1){

	}
}

void threadmain2(void){
	while(1){

	}

}
int main(void)
{
	/* Initialize the RTOS */
	rtos_init();
	/*Create threads*/
	rtos_svc_threadCreate(&thread1, &stack1, 1, threadmain1);
	rtos_svc_threadCreate(&thread2, &stack2, 1, threadmain2);
	/*Create mutex with released initial value*/
	rtos_svc_mutexCreate(&mutex1, 1u);
	/* Start the RTOS scheduling*/
	rtos_svc_schedulerStart();
	/* Loop forever */
	while(1){}
}
